## Load Numpy


In [2]:
import numpy as np

## Basics

In [3]:
a = np.array([1,3,4,5,6,8,7], dtype='int16')
print(a)

[1 3 4 5 6 8 7]


In [4]:
# 2D array of floats(nesting lists)
b = np.array([[9.0,8.7,3.1],[3.9,2.8,1.0]])
print(b)

[[9.  8.7 3.1]
 [3.9 2.8 1. ]]


In [5]:
## Get dimensions
b.ndim

2

In [6]:
#get shape(it's a 2/3 matrix)
b.shape

(2, 3)

In [7]:
#Get type(int16 takes less space)
a.dtype

dtype('int16')

In [8]:
b.dtype

dtype('float64')

In [9]:
#Get size
a.itemsize

2

In [10]:
b.itemsize

8

In [11]:
#Get total size
a.nbytes

14

## Accessing/changing specific rows and columns 

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
#Get a specific element[r,c], getting 13 from this list
a[1, 5]

13

In [14]:
#can also use negative elements, *negative elements starts from the right side from -1 not 0.
a[1, -2]


13

In [15]:
a[0, -4]

4

In [16]:
# Get a specific row ( basic slice syntax for all columns ':')
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Get a specific column ( basic slice syntax for all rows ':')
a[:, 3]

array([ 4, 11])

In [18]:
#Getting elements in a fancy way [ startindex:endindex:stemsize]
a[1, 1:6:2]

array([ 9, 11, 13])

In [19]:
#another way of doing this is ->
a[1, 1:-1:2]

array([ 9, 11, 13])

In [20]:
# Change elements (for example I want to change 6 in 1st row to 40)
a[0,5] = 40
print(a)

[[ 1  2  3  4  5 40  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# if wanna change a entire column 
a[:, 4] = [8,7]
print(a)

[[ 1  2  3  4  8 40  7]
 [ 8  9 10 11  7 13 14]]


### 3D example

In [22]:
b = np.array([[[1,2],[2,4]], [[4,6],[8,9]]])
print(b)

[[[1 2]
  [2 4]]

 [[4 6]
  [8 9]]]


In [23]:
#Get specific element (recomendation is work outside in)
b[0,1,1]

4

In [24]:
# To get the second row from each set 
b[:,1,:]

array([[2, 4],
       [8, 9]])

In [25]:
# replace (NOTE: as long as it is in the same dimension it will work)
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[4 6]
  [8 8]]]


## Initializing different types of arrays

In [26]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# All 1s matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [28]:
# Any other numbers
np.full((2,3), 87)

array([[87, 87, 87],
       [87, 87, 87]])

In [29]:
# Any other number (full_like) makes a shape just like list 'a' with the values 7
np.full_like(a,7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [30]:
# Random decimal numbers
np.random.rand(3,3,4)
# To give a specific shape 
np.random.random_sample(a.shape) 

array([[0.73895188, 0.96981867, 0.9606601 , 0.87808291, 0.89845674,
        0.44590228, 0.08790096],
       [0.31866959, 0.13787307, 0.69302842, 0.45181871, 0.28825006,
        0.52665879, 0.98093255]])

In [31]:
# Random integer values
np.random.randint(7, size=(3,4))

array([[0, 4, 6, 6],
       [6, 1, 5, 2],
       [3, 2, 2, 0]])

In [32]:
# Identity matrix(by nature its a square)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Making a martix

In [34]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying numpy array

In [35]:
a = [1,2,3]
b = a.copy()
print(b)

b[0] = 100
print(b)
print(a)

[1, 2, 3]
[100, 2, 3]
[1, 2, 3]


### Mathematics

In [36]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
# subtraction
a - 2

array([-1,  0,  1,  2])

In [38]:
# Addition
a + 2

array([3, 4, 5, 6])

In [39]:
# Multiplication
a * 2

array([2, 4, 6, 8])

In [40]:
# Division
a / 2

array([0.5, 1. , 1.5, 2. ])

In [41]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [42]:
# Square 
a ** 2

array([ 1,  4,  9, 16])

In [43]:
# Take the sin of all value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [44]:
# cosof all value
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Statistics ( min, max, avg etc)

In [46]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

1

In [48]:
np.max(stats)

6

In [49]:
# to get min of 1st row and min of second row 
np.min(stats, axis = 1)

array([1, 4])

In [52]:
np.max(stats, axis = 1)

array([3, 6])

### Reorganizing arrays

In [62]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
